version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV
      - OPENAI_API_KEY
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --skip-character-set-client-handshake

volumes:
  mysql_data:
