version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: backend
      MYSQL_USER: joon
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --skip-character-set-client-handshake

volumes:
  mysql_data:
